# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: aws-ps

stages: 
- stage: build
  displayName: Build Stage
  jobs:
  - job: build
    displayName: Build Qubic
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
                docker build -t minerlab-portal:$(Build.BuildId) .

- stage: staging
  dependsOn: build
  displayName: staging
  jobs:
  - job: deploy
    displayName: deploy staging
  - deployment:
    environment:
      name: "staging"
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                  env=staging tag=$(Build.BuildId) docker compose -p minerlab-portal up -d --force-recreate staging

- stage: prod
  dependsOn: staging
  displayName: Deploying to Prod
  jobs:
    - job:
      displayName: 
    - deployment:
      environment:
        name: "Prod"
      strategy:
        runOnce:
          deploy:
            steps:
            - task: Bash@3
              displayName: Deploy to Production
              inputs:
                targetType: 'inline'
                script: |
                        env=prod tag=$(Build.BuildId) docker compose -p minerlab-portal up -d --force-recreate prod
