version: '3'
services:
  staging:
    # container_name: ps-frontend-${env}
    # image: minerlab-portal:${tag}
    image: minerlab-portal:${tag}
    ports:
      - 5100:3000
  prod:
    # container_name: ps-frontend-${env}
    image: minerlab-portal:${tag}
    ports:
      - 4100:3000
  #   # build: ./
  #   # tty: true
  #   # volumes:
  #     # - ./data:/app/data
